/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'date' : Time,
  'author' : string,
  'category' : string,
}
export interface Enquiry {
  'country' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Event {
  'title' : string,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface Testimonial {
  'country' : string,
  'studentName' : string,
  'text' : string,
  'university' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addBlogPost' : ActorMethod<[BlogPost], bigint>,
  'addEvent' : ActorMethod<[Event], bigint>,
  'addTestimonial' : ActorMethod<[Testimonial], bigint>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitEnquiry' : ActorMethod<[Enquiry], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];