/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
  'category' : IDL.Text,
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'country' : IDL.Text,
  'studentName' : IDL.Text,
  'text' : IDL.Text,
  'university' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Enquiry = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [IDL.Nat], []),
  'addEvent' : IDL.Func([Event], [IDL.Nat], []),
  'addTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitEnquiry' : IDL.Func([Enquiry], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'country' : IDL.Text,
    'studentName' : IDL.Text,
    'text' : IDL.Text,
    'university' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Enquiry = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [IDL.Nat], []),
    'addEvent' : IDL.Func([Event], [IDL.Nat], []),
    'addTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitEnquiry' : IDL.Func([Enquiry], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };